
#---------GEMINI API KEY------#
API_KEY = "AIzaSyAXpJ0WKrEK8dImyXCU14tfwG8210Hex_Y"

#---------SAMBUNGIN KE DATABASE ------#
[mysql]
host = "localhost"
user = "root"
password = ""
database = "chatsehat_db"